Added module code
OS2Forms/os2forms_get_organized pull request #1
Opened 2023-03-15 12:49 UTC by jekuaitk

2023-03-22 12:01 UTC, stankut requested changes

2023-03-22 12:01 UTC, stankut commented on src/Form/SettingsForm.php
> +final class SettingsForm extends FormBase {
what is the reason for making this class final?

2023-03-22 12:01 UTC, stankut commented on src/Helper/Settings.php
> +final class Settings {
is there any specific idea behind introducing a custom class/way of string the Settings?

It seems like classic Config would do just fine here, and it does not require extra classes. Unless i am missing some idea behind it

quick tutorial: https://www.drupal.org/docs/drupal-apis/configuration-api/working-with-configuration-forms

2023-03-22 12:01 UTC, stankut commented on src/Plugin/AdvancedQueue/JobType/ArchiveDocument.php
> +final class ArchiveDocument extends JobTypeBase implements ContainerFactoryPluginInterface {
i see that , the making the custom classes final is just a matter of style. But IMO that is redundant, perhaps

2023-03-22 12:01 UTC, stankut commented on src/Exception/AttachmentElementNotFoundException.php
> +class AttachmentElementNotFoundException extends \Exception {
didn't find it being used. Is it needed?

2023-03-22 12:01 UTC, stankut commented on src/Helper/ArchiveHelper.php
> +use ItkDev\GetOrganized\Client;
is that an unmentioned dependency? Was able to find it anywhere, same goes for all ItkDev\GetOrganized classes

2023-03-22 12:01 UTC, stankut commented on os2forms_get_organized.info.yml
> +  - drupal:advancedqueue
missing dependency: webform_entity_print_attachment

2023-03-22 14:48 UTC, jekuaitk commented on os2forms_get_organized.info.yml
> +  - drupal:advancedqueue
Added dependency in eb82f746b7a5587ff3a6ad31b2d12276ac261ec6.

2023-03-22 14:53 UTC, jekuaitk commented on src/Helper/ArchiveHelper.php
> +use ItkDev\GetOrganized\Client;
From my understanding non drupal module package [dependencies](https://www.drupal.org/docs/develop/creating-modules/let-drupal-know-about-your-module-with-an-infoyml-file#s-complete-example) are not included in `os2forms_get_organized.info.yml`, but instead just required through `composer.json`.

2023-03-22 14:54 UTC, jekuaitk commented on src/Exception/AttachmentElementNotFoundException.php
> +class AttachmentElementNotFoundException extends \Exception {
Good catch. Removed in eb82f746b7a5587ff3a6ad31b2d12276ac261ec6.

2023-03-22 14:55 UTC, jekuaitk commented on src/Plugin/AdvancedQueue/JobType/ArchiveDocument.php
> +final class ArchiveDocument extends JobTypeBase implements ContainerFactoryPluginInterface {
It is indeed redundant. Changed in eb82f746b7a5587ff3a6ad31b2d12276ac261ec6.

2023-03-22 14:55 UTC, jekuaitk commented on src/Form/SettingsForm.php
> +final class SettingsForm extends FormBase {
It is indeed redundant. Removed in eb82f746b7a5587ff3a6ad31b2d12276ac261ec6.

2023-03-22 15:33 UTC, jekuaitk commented on src/Helper/Settings.php
> +final class Settings {
I did consider doing this via config, but ultimately decided against it. In my opinion doing it the config way just gives us the hassle of having to tread carefully when config exporting etc.

2023-03-27 13:23 UTC, stankut commented on src/Helper/ArchiveHelper.php
> +use ItkDev\GetOrganized\Client;
right, i didn't notice it in composer.json

2023-03-27 13:58 UTC, stanbellcom commented on src/Form/SettingsForm.php
> +final class SettingsForm extends FormBase {
i don't see it removed in https://github.com/OS2Forms/os2forms_get_organized/commit/eb82f746b7a5587ff3a6ad31b2d12276ac261ec6

2023-03-27 13:58 UTC, stankut commented on src/Form/SettingsForm.php
> +final class SettingsForm extends FormBase {
great, will you also remove it for `class GetOrganizedWebformHandler` ?

2023-03-27 14:01 UTC, stanbellcom commented on src/Helper/Settings.php
> +final class Settings {
yes, i see your point, 
however other contrib modules are using that as simple config object without any second thoughts: https://git.drupalcode.org/project/smtp/-/blob/8.x-1.x/src/Form/SMTPConfigForm.php#L107

i will leave it up to you.

2023-03-27 14:41 UTC, jekuaitk commented on src/Form/SettingsForm.php
> +final class SettingsForm extends FormBase {
My bad - they are now removed.

2023-03-28 07:59 UTC, stanbellcom approved these changes

2023-03-29 06:35 UTC, merged